### PR TITLE
Pass variant base when saving an attribute.

### PR DESCRIPTION
**Pull request by dmolineus**
This pull request provides a fix for #871. Non variant field were exlcluded when updating an variant. This leads to an issue when cloning variants because the base values will get lost. Instead of excluding them they are always refreshed from the base which shouldn't hurt.

### CODE REVIEW

**Comment by stefanheimes** [comment]
Hmm this line seems to be wrong. 
https://github.com/dmolineus/metamodels-core/blob/fix/cloning-variants/src/MetaModels/MetaModel.php#L915 

We checking the item and base, this two vars come from the caller. So we have no need to check it for each attribute. If the argument is true we can return and so we can add this function at the start of the function. This will save some rounds in the foreach.

**Comment by dmolineus** [comment]
You are right. It was definitely too late last night... I think the fetching of the base can be removed as well as when a variant exists the base should exist as well.

**Comment by dmolineus** [comment]
Okay, I updated this pull request. It's required to update the base attributes as well when creating a new variant mainly when duplicating them.

**Comment by stefanheimes** [comment]
Local test seems to be okay, in the first moment.

**Comment by discordier** [comment]
@stefanheimes Is this good to merge then?

**Comment by discordier** [comment]
@stefanheimes BUMP!!!!!

**Comment by tim-bec** [comment]
@stefanheimes @discordier  Please be so kind and take a look at this issue. A fix in the core would be very helpful for us.

**Comment by xantippe** [comment]
@all: wie gehts hier weiter?!?

**Comment by discordier** [comment]
@xantippe: waiting patiently for report from @stefanheimes and/or other testers.

**Comment by stefanheimes** [comment]
Under testing with the current hotfix versions of MM-Core and DCG.

**Comment by discordier** [comment]
@stefanheimes merge to beta branch at will.

**Comment by discordier** [comment]
Merged with 3a12beb

**Pull request closed without merging**
