### PR TITLE
Hotfix sorting for multilanguage attributes

### PR DESCRIPTION
**Pull request by zonky2**
## Description

The sorting at other languages as the fallback language are inconsitent.
## Checklist
- [ ] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

@discordier: thanks for the "support" ;-)

### CODE REVIEW

**Comment by discordier** [comment]
I am not quite sure that is is completely correct.

We are now totally ignoring the filter procedure by the attribute. We will have to test the implementing classes first prior merging.

**Comment by zonky2** [comment]
@discordier Which "filter procedure" do you mean?

**Comment by discordier** [comment]
> Which "filter procedure" do you mean?

The one deleted [here](https://github.com/MetaModels/core/pull/1046/files#diff-6be462b4711969007de39d1d62527525L263)

**Comment by zonky2** [comment]
o.k. ... 
we have with 
https://github.com/MetaModels/core/pull/1046/files#diff-6be462b4711969007de39d1d62527525R272
and
https://github.com/MetaModels/core/pull/1046/files#diff-6be462b4711969007de39d1d62527525R279

plus
https://github.com/MetaModels/core/pull/1046/files#diff-6be462b4711969007de39d1d62527525R265
and
https://github.com/MetaModels/core/pull/1046/files#diff-6be462b4711969007de39d1d62527525R277

the same functionality as https://github.com/MetaModels/core/blob/2909ef20be3c5e5c9e8da7db11931d75060d07f3/src/MetaModels/Attribute/TranslatedReference.php#L53-L61

the ony probmlem what I see is at https://github.com/MetaModels/core/blob/2909ef20be3c5e5c9e8da7db11931d75060d07f3/src/MetaModels/Attribute/Base.php#L87
```parameterMask``` expect an array and ```$idList``` can be a single value...

e.g. we can change to
```diff
-                                    $this->parameterMask($idList),             // 4
+                                    $this->parameterMask((array)$idList),  // 4
```

**Comment by discordier** [comment]
Merged in fd44c511434eb8a80d81de2a270902893c03bd19

**Pull request closed without merging**
