### PR TITLE
Sanitize input parameters

### PR DESCRIPTION
**Pull request by richardhj**
## Description

Fix fixme.
Needs testing, I guess.

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [x] Created tests, if possible
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by zonky2** [comment]
https://github.com/MetaModels/core/issues/1147

**Comment by discordier** [comment]
I doubt we can do this in C4. Well, we can but should not, as the input is from another request in there then.

**Comment by discordier** [comment]
@richardhj do you want to reopen or do we scrap this up?

**Comment by richardhj** [comment]
As you raised you concerns belonging to Contao 4, we can lay the PR aside

**Comment by discordier** [comment]
fine with me. :)

**Pull request closed without merging**
