### PR TITLE
Hotfix #965 fix the moving of the icons on top

### PR DESCRIPTION
**Pull request by zonky2**
## Description

Hotfix #965 fix the moving of the icons of the first instead of the navigation

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

## Screenshot

current
shot163

with hotfix
... with child table
shot164

... with BE integration
shot165

... with DCA-Config ```dcaconfig.php```

```
<?php

/* change label  */
$GLOBALS['TL_LANG']['MOD']['metamodel_mm_mitarbeiterliste'] = array('MA (DCA-Anpassung)', 'MM Test.');

/* on top */
$GLOBALS['BE_MOD']['content'] = array_merge(
  array('metamodel_mm_mitarbeiterliste' => array(
      'tables' => array('mm_mitarbeiterliste'),
      'icon' => 'files/metamodels/icons/accept.png'
  )),
  $GLOBALS['BE_MOD']['content']  
);
```

shot167

### CODE REVIEW

**Comment by xantippe** [comment]
@discordier ich habe bei den "Helpern" von MM mal nachgesehen, aber keinen gedunden, wo man das "array_merge_recursive_unique" unterbringen könnte... bei Contao-Core gibt es eine ähnliche Funktion leider auch nicht :-(

**Comment by discordier** [comment]
Should be fixed by 437e8b6

**Comment by zonky2** [comment]
with your fix include the icon at end of the list, but it´s not possible to work with the dcaconfig.php

we should use the array_merge_recursive_unique at future...

in my mind, we have 50%...

**Comment by discordier** [comment]
You wanted to finish it a long time ago, we needed an immediate solution.
50% is done, now you have time to finally finish the new repository.

**Comment by discordier** [comment]
@zonky2 As you did not work on this anymore, I'm closing this now.

**Comment by zonky2** [comment]
I wait of the "DCG Toolbox" with the recursive array merger..

**Comment by discordier** [comment]
You were/are in charge of developing it?!?!

**Pull request closed without merging**
