### PR TITLE
hotfix usage inserttags in filter set idList

### PR DESCRIPTION
**Pull request by zonky2**
hotfix usage inserttags in filter set idList

### CODE REVIEW

**Comment by discordier** [comment]
I fail to see the reason, benefit and usecase here.

**Comment by zonky2** [comment]
this is a part for https://community.contao.org/de/showthread.php?53090-MetaModels-Pagination-Random

* I generate a list with random Itemes and save in sesseion as id-list
* to use the pagination options, I set the list in a static filter rule

**Comment by richardhj** [comment]
My fears are that the replacement of insert tags is a very time-consuming task.

**Comment by zonky2** [comment]
>My fears are that the replacement of insert tags is a very time-consuming task.

... not more as all other insert tags of metaModels or Contao core!

**Comment by zonky2** [comment]
MM-call 26.09.2017: we should create a own filter rule

**Pull request closed without merging**
