### PR TITLE
Remove the front end editing fragments from the core template and rework "actions" in the list template

### PR DESCRIPTION
**Pull request by richardhj**
## Description

Add the variable createEnable to the MetaModel list template. There is no need to show the addUrl button if the table is not creatable.
See MetaModels/contao-frontend-editing#7

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [x] Created tests, if possible
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by discordier** [comment]
the corresponding PR in FE editing needs to be adjusted, then we can safely merge this one.

**Comment by richardhj** [comment]
After merging #1082 using an own template is possible too.
Like 
```html
<?php $this->extend('ce_metamodel_list); ?>

<?php $this->block('content'); ?>
<?php if ($this->editEnable): ?>
<div class="addUrl"><a href="<?= $this->addUrl ?>"><?= $this->addNewLabel ?></a></div>
<?php endif; ?>

<?php $this->parent(); ?>
<?php $this->endblock(); ?>
```

**Comment by discordier** [comment]
I guess we should then rather follow that way, what do the others think?
@MetaModels/team

**Comment by zonky2** [comment]
> ...that way...

Which way? the way to extend?

**Comment by discordier** [comment]
> Which way? the way to extend?

Yes, as proposed by @richardhj, own template extending the base template and adding the relevant button.

**Comment by discordier** [comment]
@richardhj This now conflicts due to the template inheritance changes. Could you update the PR with the custom template we discussed?

**Comment by zonky2** [comment]
Hi @richardhj and @discordier - ist ready to merge?

**Comment by richardhj** [comment]
I moved the front end editing fragments to the corresponding package.
However I want to request something:
Instead of hardcoding the buttons like …
```php
//@see https://github.com/MetaModels/core/blob/hotfix/alpha-15/contao/templates/metamodel_prerendered.html5
<?php $this->block('actions'); ?>
<?php if ($arrItem['jumpTo']['deep']): ?>
<a href="<?= $arrItem['jumpTo']['url'] ?>"><?= $this->details ?></a>
<?php endif; ?>
<?php $this->endblock(); ?>
```
… I propose to make it more dynamically. For example a `BuildMetaModelListActionsEvent` event could be introduced and custom extensions can modify the action buttons that will be added to the templates. I use this solution as proposed in one project already.

**Comment by discordier** [comment]
@richardhj fine for me, can you share the implementation details?

**Comment by richardhj** [comment]
Can be merged in combination with MetaModels/contao-frontend-editing#7. Please have a look at my latest comment at the referenced PR (with the idea of adding an event listener to pre-select the right template).
Both pulls will a) refactor the FEE fragments from core to the FEE package and b) add an `isCreatable` var to hide the add_new button when necessary.

I provide a new PR corresponding to https://github.com/MetaModels/core/pull/1078#issuecomment-289604497.

**Comment by richardhj** [comment]
With f345a231d41481ac9c8027b659968b1abfa3bd9f, an `actions` array is added to the `$arrResult`. This is modifiable by the `ParseItemEvent`. Every (third party) extension, including the FEE can add his buttons.

**Comment by discordier** [comment]
@richardhj could you squash the commits and rebase against current alpha15?
Then we are ready to merge this thing (if @stefanheimes has no objections).

**Comment by richardhj** [comment]
👍

**Comment by discordier** [comment]
Merged, thanks for your efforts!

**Comment by zonky2** [comment]
@richardhj how can I found the `jumpTo`?

https://github.com/MetaModels/core/blob/hotfix/2.0.0-alpha16/contao/templates/metamodel_prerendered.html5#L20-L25

**Comment by richardhj** [comment]
Via $arrItems['actions']['jumpTo']. $arrItems['jumpTo'] is legacy.

**Comment by zonky2** [comment]
thx

**Pull request merged**
