### PR TITLE
Introduce `IItem::getVariantBase()`

### PR DESCRIPTION
**Pull request by richardhj**
## Description

Introduce the `IItem::getVariantBase()` as described in #237.

Unit tests for `IItem::getVariants()`, `IItem::isVariant()`, `IItem::isVariantBase()`, `IItem::getVariantBase()` unneeded?

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by zonky2** [comment]
current year is 2017 ;-)

**Comment by discordier** [comment]
> Unit tests for `IItem::getVariants()`, `IItem::isVariant()`, `IItem::isVariantBase()`, `IItem::getVariantBase()` unneeded?

Unit tests are always needed, however they are most times omitted because the dev was too lazy. :smile:
I'd be happy if you could add them (and if possible even more) over the time.

**Comment by zonky2** [comment]
hi @richardhj it´s possible to write the unit test? we should merge the PR asap

**Comment by richardhj** [comment]
I'm not sure what the unit tests should cover.

**Pull request merged**
