### PR TITLE
Hotfix searchable pages add breadcrumb

### PR DESCRIPTION
**Pull request by zonky2**
## Description

Add breadcrumb at backend for searchable pages (indexing) - look at #905

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

Test:
shot175

to-do: update Transifex

### CODE REVIEW

**Comment by discordier** [comment]
Merged with 193da22

**Comment by zonky2** [comment]
hotfix11 works fine... but I cant find the String ```All indexes of``` at transifex..?

shot196

**Comment by discordier** [comment]
It will become available when it has been merged to master.
Currently translations are handled on the master branch only.

This will change when MiniModel get's updated to the next version, until then, patience please.

**Comment by zonky2** [comment]
o.k.

**Pull request closed without merging**
