### PR TITLE
Fix performance issue

### PR DESCRIPTION
**Pull request by binron**
Add arrAttrOnly parameter to the $this->getMetaModel()->findById call
In my case it reduced the number of queries from 9005 to 382 (see Screenshots)!

IMPORTANT: https://github.com/contao-community-alliance/dc-general/pull/305
needs to be fixed first

screen shot 2016-09-02 at 10 20 46
screen shot 2016-09-02 at 10 21 18

### CODE REVIEW

**Comment by zonky2** [comment]
pls add your sign at https://github.com/MetaModels/core/blob/master/.check-author.yml

**Comment by binron** [comment]
I did it. Hope that it's fine now.

**Comment by discordier** [comment]
@zonky2 did you give this a test run?
I suspect we will loose some field values in the Backend somewhere in dc-general along the way.

To clarify, the proposed change is fixing a real problem and is correct but I want to make sure that we do not loose any functionality along the way which resulted from "bug riding" this.

**Comment by zonky2** [comment]
@binron how can I test it?

**Comment by binron** [comment]
@zonky2
We need to check code which calls MetaModels\DcGeneral\Data\Driver::fetch()
if $objConfig->getFields() is empty nothing changes at all
if it's not empty but lacks some required fields it would be a problem

I couldn't find any problems 'til now
but I agree that we have to be careful not to break something else

**Comment by discordier** [comment]
To preproduce the bug (which can be triggered by contao-community-alliance/dc-general#305):

1. Enable translation with some languages.
2. Add a `translated-checkbox` attribute.
3. Mark said attribute as published field.
4. Add some foreign referencing attributes (`select` or `tags`).

If theses steps are applied, you should get the behaviour outlined in the output above.

**Comment by zonky2** [comment]
tested:

|Type           |before|after |
|DB Queries |1073  |467  |
|Rows          |2299  |1693|

**Comment by binron** [comment]
@zonky2 if you test it with more languages, more entries and more `select` or `tag` attributes
the difference will be even greater (in my case it was more than 20 times less!)

**Comment by dennishpunkt** [comment]
I also tested it:
Before: 8s / 3866 Queries / 20315 Rows
After: 2s / 482 Queries / 17299 Rows

It seems like there's still a huge overhead. It's just a result set of 30 entries with two cols. I'm using tag relations to other metamodels. These have also relations to other mm. I can still see many queries to the related tables and assets (i.e. files in other mm, translated texts). But this fix already helps a lot, makes the system useable again. 

@zonky2 Thanks for your hint!

**Comment by discordier** [comment]
Merged in 7ecf0461fc392449090cec2999ef0e988bad0280, thank you for tracking this down.

**Pull request closed without merging**
