### PR TITLE
fix language property to underscore to be compatible to contao core

### PR DESCRIPTION
**Pull request by Zeromax**
see #756

### CODE REVIEW

**Comment by MrTool** [comment]
+1
same behavior as in contao:
https://github.com/contao/core/blob/960155bf2c6225cdf2f3d2f21fb9ae9492f86a11/system/modules/core/library/Contao/System.php#L250

This PR also fixes #739

**Comment by Zeromax** [comment]
I don't think this fixes #739 I think #755 fix this, because it is not possible to set up a translated Attribute with a language var longer than 2.

**Comment by Zeromax** [comment]
As discussed with @discordier it is better to save the language code with a `-` in the Database.
So it is not necessary to replace it here.

**Comment by Zeromax** [comment]
Note for myself:
https://github.com/MetaModels/core/blob/tng/src/MetaModels/MetaModel.php#L564
https://github.com/MetaModels/core/blob/tng/src/MetaModels/MetaModel.php#L578

replace the `_` with a `-` here.
-> see https://github.com/contao/core/blob/master/system/config/languages.php
So the check with the current language should work.

Each model which is loading the language in the back end is using the `underscore`. `$GLOBALS['TL_LANGUAGE'])` contains ther __real__ language string like `de-DE`

**Comment by Zeromax** [comment]
Question @discordier:
Should this: https://github.com/MetaModels/core/blob/tng/src/MetaModels/MetaModel.php#L596 return the active language of the current MetaModel detected by the "active" language and the fallback?

Or there should be a method which Returns the current language based on active and fallback language...

**Comment by discordier** [comment]
@Zeromax Sorry for the long time to answer this.
I am not sure if I get your question right so I try to answer as best as I can.
The method is meant to determine the current language the MetaModel is currently configured to retrieve values in. This (sadly) is currently mapped to the "Contao" language currently active.
However, this method is NOT meant to perform the automatic fallback to return the fallback language as if it would do so, there would be no way to separate the active language configured from the fallback language if no values are available in the configured language.

Some time ago I thought about keeping this value as private property in the MetaModel and adding a setLanguage() method but this will require many changes in many places and therefore I'd prefer to separate the whole value retrieval from the MetaModel class into a Item retriever (like Doctrine Repositories) which will get the requested language and fallback language passed then and perform retrieval accordingly.

**Pull request closed without merging**
