### PR TITLE
Hotfix update template text

### PR DESCRIPTION
**Pull request by zonky2**
update template text and delete ':' because laguage string include this https://github.com/MetaModels/core/blob/08b502234efe150003450cf01b5611b00f9ebd57/contao/languages/en/default.php#L61

### CODE REVIEW

**Comment by richardhj** [comment]
What kind of quote char was used originally? And after your update?

**Comment by zonky2** [comment]
before we have:

```
Name:: Mayer
E-Mail:: mayer@mm.com
```

after https://github.com/MetaModels/core/pull/1168/commits/7b8c0419228b52c3e8a640f2c77ea77768962a01

```
Name: Mayer
E-Mail: mayer@mm.com
```

**Comment by richardhj** [comment]
Nope, I meant the changes of 56ebd4a.

**Comment by discordier** [comment]
Can you elaborate?

**Comment by zonky2** [comment]
@discordier ?

**Comment by discordier** [comment]
> ah... o.k. - this commit is from #1166 and den krieg ich nicht los hier so ein mist

What do you mean by this? What can't you get rid of?

**Comment by discordier** [comment]
Do we really need to append the trailing space?

**Comment by richardhj** [comment]
@discordier this is a text template, no css possible.

**Pull request merged**
