### PR TITLE
#1098 Update to work with DCG edit/overrideAll

### PR DESCRIPTION
**Pull request by baumannsven**
This is for ticket:
https://github.com/MetaModels/core/issues/1098

### CODE REVIEW

**Comment by stefanheimes** [comment]
Merged with 8e61ba89a336e59996f5a5245370c2b8476efea5

**Comment by stefanheimes** [comment]
okay something didn't work with this PR. If i see it right, this PR isn't part of the master branch. So i can't merge it back into the master, so i can't published it now. You PR was against the "item-persister-and-retriever" which is 194 ahead of the master. The current hotfix branch is wrong too. It's part of the "item-persister-and-retriever" so i am able to merge it back in the "item-persister-and-retriever" branch but not in the master. 

See the network map maybe something is wrong. @discordier Need your help pls.

**Comment by zonky2** [comment]
@baumannsven pls change to master

**Comment by stefanheimes** [comment]
Nope, please make the changes against the master branch and not against the hotfix branch. How i explain, the hotfix branch is wrong too.

**Comment by zonky2** [comment]
merged in hotfix/alpha15 (+master)

**Pull request closed without merging**
