### PR TITLE
Add TD  to $arrOptions

### PR DESCRIPTION
**Pull request by DaniloBenevides**
## Description

Add TD like orientation on issue #1162;

## Checklist
- [ ] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [ ] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by richardhj** [comment]
Hello @DaniloBenevides 
Thank you for your contribution. I would suggest @zonky2 as a reviewer.

Every time you commit on GitHub for this project, Travis runs in the background. When you check it, you will see the following message:
```
-check-author-validation.installed:
author-validation:
[author-validation] The file /home/travis/build/MetaModels/core/src/MetaModels/Widgets/SubDcaWidget.php is not mentioning its author(s):
[author-validation] Danilo Benevides …
Target 'author-validation' failed with message 'exec returned: 1'.
Cannot execute 'verify' - 'author-validation' failed or was not executed.
```
So, every time you contribute to MetaModels, you have to add your author tag line in the PHPDoc. Check for your correct mail address. :-)

**Comment by DaniloBenevides** [comment]
Hello guys ! Thanks a lot for the patience and support.
I made the changes but Travis still have problems to make the build. 
Am i doing something wrong ?

**Comment by zonky2** [comment]
@DaniloBenevides ... and update the year of 2017 ;-)

**Comment by DaniloBenevides** [comment]
Done :)

**Comment by richardhj** [comment]
> I made the changes but Travis still have problems to make the build.
> Am i doing something wrong ?

Errors given in Travis are out of the scope of files you touched. So fine up to here.

**Comment by discordier** [comment]
Merged in c16a7c3

**Pull request closed without merging**
