### PR TITLE
support for delete a attribute and his translated

### PR DESCRIPTION
**Pull request by baumannsven**
An attribute is deleted, the corresponding translated attributes was not deleted.

### CODE REVIEW

**Comment by zonky2** [comment]
tested with transleted_text => works fine and clear the table...

**Comment by discordier** [comment]
@zonky2 I hope it does not clear the table. It is supposed to only remove the referenced items in the other tables.

**Comment by zonky2** [comment]
> @zonky2 I hope it does not clear the table. It is supposed to only remove the referenced items in the other tables.

clear the colums with the coresponding att_id ;-)

**Comment by discordier** [comment]
Merged in b0b725389c3658288211bd978ed7f544148e66af

**Pull request closed without merging**
