### PR TITLE
[RTM] Fix different max length definition of DCA name fields in SQL and eval array

### PR DESCRIPTION
**Pull request by cliffparnitzky**
## Description

Some DCA fields have different max length definition in SQL and eval array. This leads for example to cutted text when saving to the database.

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [ ] Created tests, if possible
- [ ] All tests passing
- [ ] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [ ] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by cliffparnitzky** [comment]
Currently the `name` of `tl_metamodel_attribute` has no maxlength: https://github.com/MetaModels/core/blob/master/src/CoreBundle/Resources/contao/dca/tl_metamodel_attribute.php#L299 ... maybe it is useful to limit it, as all other `name` fields have a limitation.

**Review by discordier — APPROVED** [review]
LGTM

**Comment by cliffparnitzky** [comment]
@discordier @zonky2 What about my comment https://github.com/MetaModels/core/pull/1428#issuecomment-708046762 ???

**Comment by discordier** [comment]
> Currently the `name` of `tl_metamodel_attribute` has no maxlength: https://github.com/MetaModels/core/blob/master/src/CoreBundle/Resources/contao/dca/tl_metamodel_attribute.php#L299 ... maybe it is useful to limit it, as all other `name` fields have a limitation.

I am against doing so, as this would break existing installations. An attribute perfectly working before would suddenly become invalid, and further more, get truncated in the table (as the field is currently unlimited `text` type) when limiting it.
We can do so in 3.0 earliest.

**Comment by zonky2** [comment]
> Currently the name of tl_metamodel_attribute has no maxlength: https://github.com/MetaModels/core/blob/master/src/CoreBundle/Resources/contao/dca/tl_metamodel_attribute.php#L299 ... maybe it is useful to limit it, as all other name fields have a limitation.

you can open an sepatate issue and I set this to MM 3.0

**Comment by cliffparnitzky** [comment]
I think it is not necessary. For me, it is okay.

**Pull request merged**
