### PR TITLE
[RFC] Add GitHub templates

### PR DESCRIPTION
**Pull request by discordier**
This adds the files:
* `.github/CONTRIBUTING.md`
* `.github/ISSUE_TEMPLATE.md`
* `.github/PULL_REQUEST_TEMPLATE.md`

### CODE REVIEW

**Comment by discordier** [comment]
@MetaModels/team please comment and suggest changes.

I'd love to add this to all repositories to unify bug reports

**Comment by MacKP** [comment]
nice work! Looks  complete to me :)

**Comment by cliffparnitzky** [comment]
Great idea. Thanks for the work.

Some suggestions:

**CONTRIBUTING.md**

- change "I'm really glad" to "We are really glad"
- add a reference to the corresponding templates to "Submitting issues" and "Submitting changes"

**ISSUE_TEMPLATE.md**

- add to "My environment is:" a row for "Installed MM packages" ... could be usefull, if there are unknown dependencies between packages
- change the order of the sections "Expected behaviour" and "Actual behaviour" ... its often better to describe what I have and then say, what I wanted to have

**PULL_REQUEST_TEMPLATE.md**

- everything is fine

**Comment by discordier** [comment]
Thanks for the input @cliffparnitzky. Will apply the changes.

**Comment by discordier** [comment]
I have added the changes.
However, I did not add a reference to the templates as github will show them when opening a new PR or issue to every user, therefore it seems obsolete.

Anything else I should change?

@stefanheimes what about you?

**Pull request closed without merging**
