### PR TITLE
[RTM] Update FrontendFilter.php

### PR DESCRIPTION
**Pull request by MacKP**
Parameters are not correct implemented here. @discordier knows more about this (he made this change) ;-)

## Description

Please explain the detailed changes you made here.
Reference any issue number this pull request fixes.

## Checklist
- [x] Read and understood the [CONTRIBUTING guidelines](CONTRIBUTING.md)
- [x] Created tests, if possible
- [x] All tests passing
- [x] Extended the README / documentation, if necessary
- [x] Added myself to the `@authors` in touched PHP files
- [x] Checked the changes with phpcq and introduced no new issues

### CODE REVIEW

**Comment by zonky2** [comment]
@discordier how can I test the bug?

**Comment by discordier** [comment]
@zonky2 The problem here was adding filter parameters to the request via another extension did not work anymore.

In MM 2.0, one could do the following in your extension:
```
Input::set('foo', 'bar');
```
And having a filter that listens on `foo` would then pick up the value `bar` even if it did not come from the browser.
The switching to the new `FilterUrlBuilder` in 2.1 broke this functionality by not passing the get parameters but only the slug parameters. This PR restores it.

Passing any parameter as "get" parameter in the frontend should also expose the problem.
eg. using `example.html?foo=bar` instead of `example/foo/bar.html`

**Comment by zonky2** [comment]
@discordier that was known for a long time - but you didn't want to change that...

**Comment by zonky2** [comment]
@MacKP check Travis https://travis-ci.org/MetaModels/core/jobs/614645481#L373-L377
add author

**Comment by MacKP** [comment]
@zonky2 den hatte ich extra nicht eingefügt, da ich ja nicht der author bin, sondern @discordier ...

**Comment by zonky2** [comment]
lt. Travis hast du das hochgeladen - damit bist Du auch Autor... egal wer das "diktiert" hat ;-)

**Pull request merged**
