### PR TITLE
Update Driver.php

### PR DESCRIPTION
**Pull request by MoniqueHahnefeld**
@discordier  prepared the file for you. I know the format isn't alright, but at the moment I have no time to get all this format- and codequality knowledge, or learn new tools.
https://github.com/MetaModels/core/commit/661dd03357168e3916bc9957111f488466a4c714#commitcomment-14704259

### CODE REVIEW

**Comment by discordier** [comment]
You are changing the default value, this will break all existing behaviour.

Could you elaborate why you need to change it? In the end, this is just internal handling of DCG and therefore there should arise no problems outside of DCG.
If we change this, we will need to interface it.

**Comment by MoniqueHahnefeld** [comment]
@discordier Yes I took the code from my installation, where I need this default value, because I use the langcode format like this de-DE :)

If I'll got through all the langcode bondings maybe I'm able to better explain^^

**Comment by discordier** [comment]
I have really no clue what you are doing here and why you are using `-` as separator.
Even the Contao core uses `_` to separate the language designation, which is the reason why we put it this way.

You should not need to change this at all, as it is used throughout the whole system and therefore you will have to alter all places where this is used (i.e. `dc-general/LanguageFilter`) and I really doubt that this is needed to change this at all.
You only will have to alter this once, if you need the value different when retrieving the value via `getLocale()`.

**Comment by MoniqueHahnefeld** [comment]
Yes, I changed the list of languages within the config/languages.php because I need it so...

**Comment by discordier** [comment]
As I thought, you want to change it at the wrong place.
From where is your URL parameter set in the backend? What  language filter you are talking about?
It is pretty hard to help you as you are trying to patch stuff for a concrete usecase and do not think about a generic solution.
In the end, everything is using `_` except for the FrontendUrl parameter AFAIR.

It seems all you need to do is passing a rewritten language parameter to your custom filter but as I do not know what filter you are using in the frontend, I can not help here.

**Comment by MoniqueHahnefeld** [comment]
omg. no you don't understand me I think. I set the langcode in the rootpages as usual. with language filter I mean the logic of metamodels to split the url into params and generate the sql string out of it.

**Comment by discordier** [comment]
This is done by Contao, not by MetaModels. We simply use the Input class. However, you have still not told us your filter setup. So it's hard to tell how to correctly fix your problem.

**Comment by MoniqueHahnefeld** [comment]
ok, but i understood now that's not really relevant. i worked through all the relevant classes und methods. sorry for the irritation.

**Pull request closed without merging**
